# action.yml
name: 'Validate JSON checklists'
description: 'Validate JSON Azure checklists'
inputs:
  language:  # set to 'en' to only validate English checklists
    description: 'Language of checklists to validate'
    required: false
    default: 'en'
outputs:
  number_of_checklists: # id of output
    description: 'The number of checklists linted'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.language }}
